---
version: "3"

services:
  portainer:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - radarr-data:/config
      - media-data:/data
    ports:
      - 7878:7878/tcp
    networks:
      - rn-net

networks:
  rn-net:
    name: rn-net

volumes:
  radarr-data:
    name: radarr-data
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.10.30.31,rw,nolock,soft
      device: :/mnt/nfs/docker-volumes/orion/radarr-data

  media-data:
    name: media-data
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.10.30.31,rw,nolock,soft
      device: :/mnt/vault/data