version: "3"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - UMASK_SET=022 # control permissions of files and dirs created by sonarr
      - TZ=Europe/London # timezone setting
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
    volumes:
      - /docker/sonarr/config:/config # Database and sonarr configs
      - /home/retronexus/mediaserver/data:/media
    networks:
      - gluetun-net
    depends_on:
      - gluetun
