---
version: "3"

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8070
    volumes:
      - qbittorrent-data:/config
      - data-torrents:/data
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 8070:8070/tcp
    networks:
      - rn-net

networks:
  rn-net:

volumes:
  qbittorrent-data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.10.30.31,rw,nolock,soft
      device: :/mnt/nfs/docker-volumes/qbittorrent-data
  data:
      driver: local
      driver_opts:
        type: nfs
        o: nfsvers=4,addr=10.10.30.31,rw,nolock,soft
        device: :/mnt/vault/data/torrents