version: "3"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    network_mode: bridge
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP Proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 7878:7878/tcp # radarr
      - 8989:8989/tcp # sonarr
      - 6881:6881     # qbittorrent
      - 6881:6881/udp # qbittorrent
      - 8090:8090     # qbittorrent
    volumes:
      - /docker/gluetun/config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=165.231.178.10
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=fHGPlsNkuvuyLoqKp/Yfh3R31jdGN5JWRZ5cE1aW/UM=
      - WIREGUARD_PRIVATE_KEY=CKPm/dFgLJmo4dULSC4Oy6HdIJr/F64aAN4bKy6jN1w=
      - WIREGUARD_ADDRESSES=172.24.0.2/32
      - HEALTH_VPN_DURATION_INITIAL=120s

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - UMASK_SET=022 # control permissions of files and dirs created by radarr
      - TZ=Europe/London # timezone setting
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
    volumes:
      - /docker/radarr/config:/config # Database and Radarr configs
      - /home/retronexus/mediaserver/data:/data
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - UMASK_SET=022 # control permissions of files and dirs created by sonarr
      - TZ=Europe/London # timezone setting
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
    volumes:
      - /docker/sonarr/config:/config # Database and sonarr configs
      - /home/retronexus/mediaserver/data:/data
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - UMASK_SET=022 # control permissions of files and dirs created by sonarr
      - TZ=Europe/London # timezone setting
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
    volumes:
      - /docker/prowlarr/config:/config # Database and sonarr configs
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - TZ=Europe/London # timezone setting
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
      - WEBUI_PORT=8090
    volumes:
      - /docker/qbittorrent/config:/config # Database and sonarr configs
      - /home/retronexus/mediaserver/data/torrents:/data
    network_mode: "service:gluetun"      
    depends_on:
      - gluetun
