version: "3"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    network_mode: bridge
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP Proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 7878:7878/tcp # radarr
      - 8989:8989/tcp # sonarr
      - 8787:8787     # readarr
      - 9696:9696     # prowlarr
      - 8191:8191     # prowlarr
      - 6881:6881     # qbittorrent
      - 6881:6881/udp # qbittorrent
      - 8090:8090     # qbittorrent
      - 8096:8096     # jellyfin
      - 8920:8920     # jellyfin
      - 7359:7359/udp # jellyfin
      - 1900:1900/udp # jellyfin

    volumes:
      - /src/docker-config/gluetun/config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=165.231.178.10
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=fHGPlsNkuvuyLoqKp/Yfh3R31jdGN5JWRZ5cE1aW/UM=
      - WIREGUARD_PRIVATE_KEY=CKPm/dFgLJmo4dULSC4Oy6HdIJr/F64aAN4bKy6jN1w=
      - WIREGUARD_ADDRESSES=172.24.0.2/32
      - HEALTH_VPN_DURATION_INITIAL=120s

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - UMASK_SET=022 # control permissions of files and dirs created by radarr
      - TZ=Europe/London # timezone setting
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
    volumes:
      - /src/docker-config/radarr/config:/config # Database and Radarr configs
      - /home/retronexus/mediaserver/data:/data
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - UMASK_SET=022 # control permissions of files and dirs created by sonarr
      - TZ=Europe/London # timezone setting
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
    volumes:
      - /src/docker-config/sonarr/config:/config # Database and sonarr configs
      - /home/retronexus/mediaserver/data:/data
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    restart: unless-stopped
    environment:
      - UMASK_SET=022 # control permissions of files and dirs created by sonarr
      - TZ=Europe/London # timezone setting
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
    volumes:
      - /src/docker-config/readarr/config:/config # Database and sonarr configs
      - /home/retronexus/mediaserver/data/media/books:/books
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - UMASK_SET=022 # control permissions of files and dirs created by sonarr
      - TZ=Europe/London # timezone setting
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
    volumes:
      - /src/docker-config/prowlarr/config:/config # Database and sonarr configs
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - TZ=Europe/London # timezone setting
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
      - WEBUI_PORT=8090
      - TORRENTING_PORT=6881
    volumes:
      - /src/docker-config/qbittorrent/config:/config # Database and sonarr configs
      - /home/retronexus/mediaserver/data/torrents:/data/torrents
    network_mode: "service:gluetun"      
    depends_on:
      - gluetun

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:gluetun"      
    restart: unless-stopped
    environment:
      - TZ=Europe/London # timezone setting
    depends_on:
      - gluetun

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped          
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London # timezone setting
    volumes:
      - /src/docker-config/jellyfin/config:/config
      - /home/retronexus/mediaserver/data/media:/data/media
    network_mode: "service:gluetun"      
    depends_on:
      - gluetun