version: "3"
services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - UMASK_SET=022 # control permissions of files and dirs created by sonarr
      - TZ=Europe/London # timezone setting
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
    volumes:
      - /docker/prowlarr/config:/config # Database and sonarr configs
  