# DNS Settings
# Access control list
acl trusted {
    10.10.0.0/16;
    172.0.0.0/8;
    localhosts;
    localnets;
};

options {
    directory "/var/cache/bind";

    recursion yes;                 # enables resursive queries
    listen-on { any; };
    
    # Configure forwarder where outgoing DNS queries will be sent to
    forwarders {
        1.1.1.1; // Cloudflare DNS
        8.8.8.8; // Google DNS
    };

    allow-query { any; }; 
    allow-recursion { trusted; }; # allows recursive queries from "internal" ACL   
    allow-query-cache { trusted; };
};