# DNS Settings
# Access control list
acl internal {
    10.10.0.0/16;
    172.17.0.0/16;
    172.20.0.0/16;
};

options {
    directory "/var/cache/bind";
    recursion yes;                 # enables resursive queries
    listen-on { any; };
    # Configure forwarder where outgoing DNS queries will be sent to
    forwarders {
        1.1.1.1; // Cloudflare DNS
        8.8.8.8; // Google DNS
    };
    
    allow-recursion { any; }; # allows recursive queries from "internal" ACL   
    allow-query { any; }; 
    allow-query-cache { any; };
};