version: "3"
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - UMASK_SET=022 # control permissions of files and dirs created by radarr
      - TZ=Europe/London # timezone setting
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
    volumes:
      - /docker/radarr/config:/config # Database and Radarr configs
      - /home/retronexus/mediaserver/data:/data