---
version: "3"

services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - jellyfin-data:/config
      - media-data:/data
    ports:
      - 8096:8096/tcp
    networks:
      - rn-net

networks:
  rn-net:
    name: rn-net

volumes:
  jackett-data:
    name: jackett-data  
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.10.30.31,rw,nolock,soft
      device: :/mnt/nfs/docker-volumes/orion/jackett-data

  media-data:
    name: media-data
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.10.30.31,rw,nolock,soft
      device: :/mnt/vault/data