version: "3"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    restart: unless-stopped
    environment:
      - UMASK_SET=022 # control permissions of files and dirs created by radarr
      - TZ=Europe/London # timezone setting
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
    volumes:
      - /src/docker-config/calibre/config:/config # Database and Radarr configs
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081      