version: "3.8"

services:
  sqldb:
    image: mysql:8.3
    container_name: kimai_mysql
    restart: unless-stopped
    volumes:
      - /home/retronexus/database/mysql/kimai:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=retronexus
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: --default-storage-engine innodb
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:latest
    container_name: kimai
    restart: unless-stopped
    environment:
      - ADMINMAIL=${KIMAI_ADMINMAIL}
      - ADMINPASS=${KIMAI_ADMINPASS}
      - DATABASE_URL=mysql://retronexus:${MYSQL_PASSWORD}@sqldb/kimai?charset=utf8mb4&serverVersion=8.3.0
      - TRUSTED_HOSTS=localhost,127.0.0.1
    volumes:
      - /src/public/kimai:/opt/kimai/public

  nginx:
      image: tobybatch/nginx-fpm-reverse-proxy
      container_name: kimai_nginx
      ports:
        - 8080:80
      volumes:
        - /src/public/kimai:/opt/kimai/public:ro
      restart: unless-stopped
      depends_on:
        - kimai