version: "3"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London # timezone setting
    volumes:
      - /src/docker-config/jellyfin/config:/config
      - /home/retronexus/mediaserver/data/media/movies:/data/movies
      - /home/retronexus/mediaserver/data/media/tv:/data/tv      
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped